### ISSUE TITLE
Flashlight sends spurious key events

### ISSUE THREAD

**Issue by gmanika** [rainforestapp/Flashlight-vnc#11]
Flashlight is sending spurious keypress/key release events. Analysing the protocol using Wireshark we see that typing a word like "dog", which should be six commands:

key press "d" / key release "d" / key press "o" / "key release "o" / key press "g" / key release "g"

is instead rendered as:

key press NULL / key release NULL / key press "d" / key release "d" / key press NULL / key release NULL / key press "o" / key release "o" ... and so on

The NULL is literally a 0x00 byte.

Our main suspicion is that the onTextinput is generating writeKeyEvents for the character 0x00 for some reason.

If fixed, the "Massive ugly hack" a few lines may also (probably) be removed.

**Comment by macocha** [comment]
Seems it's also solved in #26
