### ISSUE TITLE
Pasting iOS Safari

### ISSUE THREAD

**Issue by gallois** [rainforestapp/Flashlight-vnc#15]
*from asana*

So the problem is isolated to HTML text input in safari, pasting to native text widgets works fine.

Pasting works by sending the keypresses required to type the string, and the solution appears to be to send each character in the string with a greater gap inbetween them. Ghetto.

**Comment by jbarber** [comment]
Resolved by https://github.com/rainforestapp/Flashlight-vnc/commit/d7623468d15f95ac6a473453b010961785c203f8
