### ISSUE TITLE
| character is not being sent to VM

### ISSUE THREAD

**Issue by macocha** [rainforestapp/Flashlight-vnc#18]
One of the users used | (symbol from above \ not capital i) in their password and it's not getting sent to VM properly.

Example: http://sharing.rainforestqa.com/3w351J3q3M2X/o

I don't have r/w access here so it's on you @jbarber

**Comment by jbarber** [comment]
Did you replicate it?

On 11 March 2016 at 00:06, Maciej Siwek <notifications@github.com> wrote:

> One of the users used | (symbol from above \ not capital i) in their
> password and it's not getting sent to VM properly.
>
> Example: http://sharing.rainforestqa.com/3w351J3q3M2X/o
>
> I don't have r/w access here so it's on you @jbarber
> <https://github.com/jbarber>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rainforestapp/Flashlight-vnc/issues/18>.
>



-- 
Jonathan Barber

**Comment by macocha** [comment]
@jbarber yeah. It's missing from https://github.com/rainforestapp/Flashlight-vnc/blob/master/Flashlight-VNC/src/com/flashlight/vnc/VNCClient.as#L611 I assume.
