### ISSUE TITLE
Improve the SecurityErrorEvent message

### ISSUE THREAD

**Issue by jbarber** [rainforestapp/Flashlight-vnc#28]
The error message when failing to connect to the security policy is not very useful:
> An security error occurred (Error #2048). Check your policy-policy server configuration or disable security for this domain

We should change this to tell the user what they should do.

**Comment by jbarber** [comment]
The message is generated by a `SecurityErrorEvent.SECURITY_ERROR` event on the socket.

This is described [here](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/SecurityErrorEvent.html) and [here](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/Socket.html#event:securityError).

The policy is loaded with the code [here](https://github.com/rainforestapp/Flashlight-vnc/blob/7e295e17ec6a5bafbc1c60c7f183683961576e18/Flashlight-VNC/src/com/flashlight/vnc/VNCClient.as#L157). Checked with wireshark and it looks like the implementation agrees with the documentation [for loadPolicy()](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/Security.html#loadPolicyFile()). However, the signature for that function doesn't let us know if the policy was successfully loaded or not...

**Comment by jbarber** [comment]
#29 addresses this

**Comment by jbarber** [comment]
@kristen-allie FYI

**Comment by jbarber** [comment]
The message also appears when the VNC port isn't available. But only after the "An IO error occured [sic]" message.

**Comment by sweeneyapps** [comment]
@jbarber Can you check this out at the forum https://forum.rainforestqa.com/t/a-security-error-occurred-error-2048/1772/31
A tester is having problem w/ 2048 error code.

**Comment by jbarber** [comment]
@sweeneyapps my guess is that they don't have connectivity to the server, I'll chase it up in the formum thread
