### ISSUE TITLE
Copy/Paste in IE9HD failing

### ISSUE THREAD

**Issue by huynhivan** [rainforestapp/Flashlight-vnc#30]
Customer: MindBodyGreen
Customer ID: 4939

Expected Behavior: Copy/Pasting values generated by social variables captures values completely when copying and enters value correctly when pasting into VM.

Actual Behavior: Copy/pasting failing to properly capture/enter values in IE9HD; doesn't seem to occur in other IE VMs.

![screen recording 2016-10-05 at 07 37 am](https://cloud.githubusercontent.com/assets/20689411/19125543/49be6722-8aec-11e6-9dde-16b8f75bad7d.gif)

Job Group:
https://admin.rainforestqa.com/job_groups/2542104

**Comment by huynhivan** [comment]
@gallois and @macocha

**Comment by huynhivan** [comment]
https://app.intercom.io/a/apps/mfdgv5am/inbox/ivan@rainforestapp.com/conversations/6164996622

**Comment by gallois** [comment]
@huynhivan is this still an issue? If so, can you move that to JIRA?

**Comment by huynhivan** [comment]
@gallois no, I think this was an instance of our c/p protocol skipping steps but wasn't recognized as such when I reported it. We can close this
